# Generated by Django 4.1.4 on 2022-12-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_love_count_alter_post_cover_lovereact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
