# Generated by Django 4.1.4 on 2022-12-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
