# Generated by Django 4.1.4 on 2022-12-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publishedAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
