# Generated by Django 4.1.4 on 2022-12-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_publishedat_alter_post_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='createdAt',
        ),
    ]
