# Generated by Django 4.1.4 on 2022-12-21 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_lovereact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovereact',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
    ]
